# Generated by Django 6.0.5 on 2026-05-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='designation',
            new_name='institute_address',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='state',
            new_name='institute_state',
        ),
        migrations.RemoveField(
            model_name='application',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='application',
            name='phone',
        ),
        migrations.AddField(
            model_name='application',
            name='aadhaar',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='accommodation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='alternate_mobile',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS')], default='General', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='dob',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='faculty_type',
            field=models.CharField(choices=[('Faculty', 'Faculty'), ('Researcher/Non-Teaching', 'Researcher/Non-Teaching')], default='Faculty', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='highest_qualification',
            field=models.CharField(choices=[('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate'), ('M.Phil', 'M.Phil'), ('Ph.D', 'Ph.D'), ('Post Doctoral', 'Post Doctoral')], default='Graduate', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='institute_pincode',
            field=models.CharField(default='000000', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='mailing_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='mailing_pincode',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='application',
            name='mailing_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='mobile',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to='applications/photos/'),
        ),
        migrations.AddField(
            model_name='application',
            name='prev_course1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='prev_course1_center',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='prev_course1_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='prev_course2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='prev_course2_center',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='prev_course2_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='pwd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='same_as_institute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.')], default='Mr.', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
