# Generated by Django 6.0.5 on 2026-05-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_rename_designation_application_institute_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='course_type',
            field=models.CharField(blank=True, choices=[('OC', 'OC - Orientation Courses'), ('RC-I', 'RC-I - Refresher Courses'), ('SC', 'SC - Short Term Courses'), ('NEP', 'NEP')], max_length=10),
        ),
    ]
